// Re-export from new location — will be removed after full migration
export {
  createConversationFromInboxEntry,
  applyClassificationToConversation,
  listConversations,
  listConversationActions,
  getConversationById,
  addMessage,
  transitionConversation,
  updateConversationHandoff,
  updateConversationDraft,
  createConversationAction,
  approveConversationAction,
  dismissConversationAction,
  getConversationAction,
  executeConversationAction,
  convertConversationToRecords,
  applyLegacyClassificationSnapshot,
  parseConversationJsonFields,
} from "@modules/inbox/service"
