/**
 * PostgreSQL baseline tooling (NEON-02).
 *
 * ONE canonical schema, ONE derived variant, ONE generated history:
 *
 *   prisma/schema.prisma                       canonical (SQLite provider while Turso is the runtime)
 *     └─ generate-schema ─▶ generated/schema.postgres.prisma   derived: ONLY the datasource
 *                                                                provider and the client output
 *                                                                path differ (gitignored artefact)
 *          └─ generate-init ─▶ prisma/migrations-postgres/0_init/migration.sql
 *                                                                empty → target, produced by
 *                                                                `prisma migrate diff`, audited,
 *                                                                IMMUTABLE once written
 *               └─ verify ─▶ EMPTY local PostgreSQL proven empty first (read-only), then
 *                             0_init applied by THIS run, ledger checked, `migrate diff`
 *                             applied-DB → variant EMPTY, second deploy a no-op
 *
 * The variant is never hand-edited: `verify` regenerates it in memory and fails
 * on any difference, so the PostgreSQL target cannot drift from the canonical
 * schema unnoticed. The SQLite history (`prisma/migrations`) and the PostgreSQL
 * history (`prisma/migrations-postgres`) never share a directory: Prisma 7.4.1
 * does NOT refuse a cross-provider diff (it silently emits DROP/CREATE), so the
 * provider separation is enforced here and by `prisma.config.postgres.ts`.
 *
 * Baseline immutability (R3): `generate-init` writes 0_init only when it does
 * not exist; an existing byte-identical file is reported unchanged; an existing
 * DIFFERENT file is a hard failure with no override flag. Schema changes after
 * publication belong in a NEW PostgreSQL migration, never in a rewritten 0_init.
 *
 * Verify contract (R3): the database behind POSTGRES_DIRECT_URL must be EMPTY
 * and disposable. Emptiness is proven BEFORE any DDL with read-only checks
 * (a `DO` block over information_schema executed through `prisma db execute`,
 * plus `prisma migrate diff --from-empty --to-config-datasource`). The first
 * `migrate deploy` must apply `0_init` in this invocation ("No pending
 * migrations" is NOT accepted), the ledger must hold exactly one completed
 * `0_init` row, the applied database must equal the variant, and a second
 * deploy must be a no-op.
 *
 * Safety: `verify` refuses any database host that is not loopback unless
 * POSTGRES_VERIFY_ALLOW_REMOTE=1 is set explicitly. That override bypasses
 * ONLY the hostname restriction — never the empty-database requirement, the
 * ledger requirements or the baseline immutability. Turso/DATABASE_*
 * variables are removed from every child process; nothing here reads or
 * writes Turso; connection URLs are never printed.
 *
 * CLI:
 *   tsx scripts/postgres-baseline.ts generate-schema
 *   tsx scripts/postgres-baseline.ts generate-init
 *   POSTGRES_DIRECT_URL=postgresql://…@127.0.0.1:5432/empty tsx scripts/postgres-baseline.ts verify
 */

import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")

export const CANONICAL_SCHEMA_PATH = join(REPO_ROOT, "prisma", "schema.prisma")
export const POSTGRES_SCHEMA_PATH = join(REPO_ROOT, "generated", "schema.postgres.prisma")
export const POSTGRES_MIGRATIONS_DIR = join(REPO_ROOT, "prisma", "migrations-postgres")
export const POSTGRES_INIT_SQL_PATH = join(POSTGRES_MIGRATIONS_DIR, "0_init", "migration.sql")
export const POSTGRES_CONFIG_PATH = join(REPO_ROOT, "prisma.config.postgres.ts")
/** Relative to the generated schema file, i.e. `generated/prisma-postgres` — never the runtime client dir. */
export const POSTGRES_CLIENT_OUTPUT = "../generated/prisma-postgres"
export const BASELINE_MIGRATION_NAME = "0_init"

const HEADER = [
  "// GENERATED by scripts/postgres-baseline.ts — DO NOT EDIT.",
  "// Derived from prisma/schema.prisma: only the datasource provider and the",
  "// generator output path differ. Regenerate with `npm run db:postgres:schema`.",
]

export function sha256(text: string | Buffer): string {
  return createHash("sha256").update(text).digest("hex")
}

/**
 * Derive the PostgreSQL variant from the canonical schema text. Exactly one
 * `provider = "sqlite"` datasource line and exactly one generator `output`
 * line are rewritten; anything else is a hard failure (fail closed rather than
 * guess). Returns the variant and the list of rewritten line numbers.
 */
export function derivePostgresSchema(canonical: string): { schema: string; rewrittenLines: number[] } {
  const lines = canonical.split("\n")
  const providerLines: number[] = []
  const outputLines: number[] = []
  let inDatasource = false
  let inGenerator = false
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (/^datasource\s+\w+\s*\{/.test(line)) inDatasource = true
    else if (/^generator\s+\w+\s*\{/.test(line)) inGenerator = true
    else if (/^\}/.test(line)) {
      inDatasource = false
      inGenerator = false
    }
    if (inDatasource && /^\s*provider\s*=\s*"[^"]+"\s*$/.test(line)) providerLines.push(i)
    if (inGenerator && /^\s*output\s*=\s*"[^"]+"\s*$/.test(line)) outputLines.push(i)
  }
  if (providerLines.length !== 1) {
    throw new Error(`postgres-baseline: expected exactly one datasource provider line, found ${providerLines.length}`)
  }
  if (outputLines.length !== 1) {
    throw new Error(`postgres-baseline: expected exactly one generator output line, found ${outputLines.length}`)
  }
  const providerLine = lines[providerLines[0]]
  if (!/"sqlite"/.test(providerLine)) {
    throw new Error(`postgres-baseline: canonical provider is not "sqlite" — the runtime provider flip must be an explicit mission, not a derivation`)
  }
  const out = [...lines]
  out[providerLines[0]] = providerLine.replace('"sqlite"', '"postgresql"')
  out[outputLines[0]] = lines[outputLines[0]].replace(/"[^"]+"/, `"${POSTGRES_CLIENT_OUTPUT}"`)
  return { schema: [...HEADER, ...out].join("\n"), rewrittenLines: [providerLines[0] + 1, outputLines[0] + 1] }
}

/** SQLite constructs that must never appear in the PostgreSQL baseline. */
export const SQLITE_REMNANT_PATTERNS: ReadonlyArray<{ name: string; regex: RegExp }> = [
  { name: "PRAGMA", regex: /\bPRAGMA\b/i },
  { name: "DATETIME type", regex: /\bDATETIME\b/i },
  { name: "AUTOINCREMENT", regex: /\bAUTOINCREMENT\b/i },
  { name: "rowid", regex: /\browid\b/i },
  { name: "sqlite_ internals", regex: /\bsqlite_/i },
  { name: "table rebuild (new_ prefix)", regex: /CREATE TABLE "new_/ },
  { name: "INSERT INTO (data copy)", regex: /\bINSERT INTO\b/i },
  { name: "RENAME TO", regex: /\bRENAME TO\b/i },
  { name: "DROP TABLE", regex: /\bDROP TABLE\b/i },
  { name: "? placeholder", regex: /\?/ },
  { name: "strftime()", regex: /\bstrftime\s*\(/i },
  { name: "datetime()", regex: /\bdatetime\s*\(/i },
  { name: "json_extract()", regex: /\bjson_extract\s*\(/i },
]

/** PostgreSQL constructs that the fidelity-first target does not use. */
export const UNEXPECTED_POSTGRES_PATTERNS: ReadonlyArray<{ name: string; regex: RegExp }> = [
  { name: "SERIAL", regex: /\bSERIAL\b/ },
  { name: "IDENTITY", regex: /GENERATED .* AS IDENTITY/ },
  { name: "JSONB", regex: /\bJSONB\b/ },
  { name: "CREATE TYPE (enum)", regex: /\bCREATE TYPE\b/ },
  { name: "gen_random_uuid", regex: /gen_random_uuid/ },
  { name: "UUID type", regex: /\bUUID\b/ },
  { name: "DEFERRABLE", regex: /\bDEFERRABLE\b/ },
  { name: "CREATE EXTENSION", regex: /\bCREATE EXTENSION\b/ },
  { name: "TIMESTAMPTZ", regex: /\bTIMESTAMPTZ\b|WITH TIME ZONE/ },
  { name: "NUMERIC/DECIMAL", regex: /\b(NUMERIC|DECIMAL)\b/ },
]

export interface BaselineCounts {
  createTable: number
  createIndex: number
  createUniqueIndex: number
  foreignKeys: number
  onDeleteCascade: number
  onDeleteSetNull: number
  onDeleteRestrict: number
  primaryKeys: number
}

export function countBaseline(sql: string): BaselineCounts {
  const count = (re: RegExp) => (sql.match(re) ?? []).length
  return {
    createTable: count(/^CREATE TABLE /gm),
    createIndex: count(/^CREATE INDEX /gm),
    createUniqueIndex: count(/^CREATE UNIQUE INDEX /gm),
    foreignKeys: count(/FOREIGN KEY/g),
    onDeleteCascade: count(/ON DELETE CASCADE/g),
    onDeleteSetNull: count(/ON DELETE SET NULL/g),
    onDeleteRestrict: count(/ON DELETE RESTRICT/g),
    primaryKeys: count(/PRIMARY KEY/g),
  }
}

/** Static audit of a generated baseline: SQLite remnants and unexpected PostgreSQL constructs. */
export function auditBaselineSql(sql: string): string[] {
  const findings: string[] = []
  for (const { name, regex } of SQLITE_REMNANT_PATTERNS) if (regex.test(sql)) findings.push(`SQLite remnant: ${name}`)
  for (const { name, regex } of UNEXPECTED_POSTGRES_PATTERNS) if (regex.test(sql)) findings.push(`unexpected PostgreSQL construct: ${name}`)
  const identifiersOver63 = new Set((sql.match(/"[A-Za-z0-9_]{64,}"/g) ?? []).map((s) => s.slice(1, -1)))
  for (const ident of identifiersOver63) findings.push(`identifier longer than 63 characters (PostgreSQL would truncate): ${ident}`)
  return findings
}

// ─── Pure contracts (unit-tested) ───────────────────────────────────────────

/**
 * Baseline immutability. `existing` is the current 0_init on disk (null when
 * absent), `fresh` the newly generated SQL. There is deliberately no override.
 */
export function reconcileBaseline(existing: string | null, fresh: string): "write" | "unchanged" {
  if (existing === null) return "write"
  if (existing === fresh) return "unchanged"
  throw new Error(
    `postgres-baseline: ${BASELINE_MIGRATION_NAME} already exists and DIFFERS from a fresh generation (existing sha256=${sha256(existing)}, fresh sha256=${sha256(fresh)}). A published baseline is immutable: schema changes belong in a NEW PostgreSQL migration, never in a rewritten ${BASELINE_MIGRATION_NAME}.`,
  )
}

/**
 * READ-ONLY emptiness assertion, executed through `prisma db execute`. Counts
 * every base table outside the system schemas; a non-zero count raises, which
 * makes the CLI exit non-zero BEFORE any DDL. `_prisma_migrations` counts as a
 * user table on purpose: a database that already carries a ledger is not empty.
 */
export const EMPTY_DATABASE_ASSERTION_SQL = [
  "DO $$",
  "DECLARE n integer;",
  "BEGIN",
  "  SELECT COUNT(*) INTO n FROM information_schema.tables",
  "   WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('pg_catalog', 'information_schema');",
  "  IF n <> 0 THEN",
  "    RAISE EXCEPTION 'POSTGRES_BASELINE_NOT_EMPTY: % user table(s) present', n;",
  "  END IF;",
  "END $$;",
  "",
].join("\n")

/**
 * READ-ONLY ledger assertion: exactly one row, and that row is a completed,
 * single-step, non-rolled-back `0_init`.
 */
export const LEDGER_ASSERTION_SQL = [
  "DO $$",
  "DECLARE total integer; ok integer;",
  "BEGIN",
  '  SELECT COUNT(*) INTO total FROM "_prisma_migrations";',
  '  SELECT COUNT(*) INTO ok FROM "_prisma_migrations"',
  `   WHERE migration_name = '${BASELINE_MIGRATION_NAME}' AND applied_steps_count = 1`,
  "     AND finished_at IS NOT NULL AND rolled_back_at IS NULL;",
  "  IF total <> 1 OR ok <> 1 THEN",
  "    RAISE EXCEPTION 'POSTGRES_BASELINE_LEDGER_INVALID: % row(s), % valid 0_init row(s)', total, ok;",
  "  END IF;",
  "END $$;",
  "",
].join("\n")

/** The first deploy must have applied 0_init in THIS invocation. */
export function assertFirstDeployApplied(output: string): void {
  if (/No pending migrations/.test(output)) {
    throw new Error("postgres-baseline: the first migrate deploy found nothing to apply — the database was not empty (0_init already recorded). verify requires an EMPTY disposable database.")
  }
  if (!new RegExp(`Applying migration \`${BASELINE_MIGRATION_NAME}\``).test(output) || !/successfully applied/.test(output)) {
    throw new Error(`postgres-baseline: unexpected first migrate deploy output (expected ${BASELINE_MIGRATION_NAME} to be applied now):\n${redactConnectionUrls(output)}`)
  }
}

/** The second deploy must be a no-op. */
export function assertRedeployNoop(output: string): void {
  if (!/No pending migrations/.test(output)) {
    throw new Error(`postgres-baseline: second migrate deploy was not a no-op:\n${redactConnectionUrls(output)}`)
  }
}

/** `migrate diff --script` output with nothing but the empty-migration marker. */
export function isEmptyDiff(output: string): boolean {
  return output
    .split("\n")
    .filter((l) => l.trim() && !/^-- This is an empty migration/.test(l) && !/^Loaded Prisma config/.test(l))
    .length === 0
}

/** Defensive: never echo a connection string in an error message. */
export function redactConnectionUrls(text: string): string {
  return text.replace(/postgres(ql)?:\/\/[^\s'"]+/gi, "postgresql://<redacted>")
}

// ─── Process helpers ────────────────────────────────────────────────────────

function sanitizedEnv(extra: Record<string, string> = {}): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env, ...extra }
  delete env.DATABASE_URL
  delete env.TURSO_DATABASE_URL
  delete env.DATABASE_AUTH_TOKEN
  delete env.TURSO_AUTH_TOKEN
  env.DOTENV_CONFIG_PATH = "/dev/null"
  env.CHECKPOINT_DISABLE = "1"
  env.PRISMA_HIDE_UPDATE_MESSAGE = "1"
  return env
}

function runPrisma(args: string[], extraEnv: Record<string, string> = {}, input?: string): string {
  try {
    return execFileSync(join(REPO_ROOT, "node_modules", ".bin", "prisma"), args, {
      cwd: REPO_ROOT,
      env: sanitizedEnv(extraEnv),
      input,
      stdio: [input === undefined ? "ignore" : "pipe", "pipe", "pipe"],
      encoding: "utf8",
    })
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string }
    const detail = [e.stdout, e.stderr].filter(Boolean).join("\n").trim() || e.message || String(err)
    throw new Error(`prisma ${args[0]} ${args[1] ?? ""} failed:\n${redactConnectionUrls(detail)}`)
  }
}

/** Run a read-only assertion script through `prisma db execute`; throws on RAISE. */
function runAssertion(sql: string, extraEnv: Record<string, string>): void {
  runPrisma(["db", "execute", "--stdin", "--config", POSTGRES_CONFIG_PATH], extraEnv, sql)
}

function out(line: string): void {
  process.stdout.write(`${line}\n`)
}

// ─── Commands ───────────────────────────────────────────────────────────────

export function commandGenerateSchema(): string {
  const canonical = readFileSync(CANONICAL_SCHEMA_PATH, "utf8")
  const { schema, rewrittenLines } = derivePostgresSchema(canonical)
  mkdirSync(dirname(POSTGRES_SCHEMA_PATH), { recursive: true })
  writeFileSync(POSTGRES_SCHEMA_PATH, schema)
  out(`[postgres-baseline] wrote ${POSTGRES_SCHEMA_PATH} (rewrote canonical lines ${rewrittenLines.join(", ")}) sha256=${sha256(schema)}`)
  return schema
}

function assertVariantFresh(): string {
  if (!existsSync(POSTGRES_SCHEMA_PATH)) throw new Error("postgres-baseline: generated/schema.postgres.prisma is missing — run generate-schema first")
  const onDisk = readFileSync(POSTGRES_SCHEMA_PATH, "utf8")
  const fresh = derivePostgresSchema(readFileSync(CANONICAL_SCHEMA_PATH, "utf8")).schema
  if (onDisk !== fresh) throw new Error("postgres-baseline: generated/schema.postgres.prisma is STALE or hand-edited — it differs from a fresh derivation of prisma/schema.prisma")
  return onDisk
}

export function commandGenerateInit(): void {
  assertVariantFresh()
  const sql = runPrisma(["migrate", "diff", "--from-empty", "--to-schema", POSTGRES_SCHEMA_PATH, "--script"])
  const findings = auditBaselineSql(sql)
  if (findings.length > 0) throw new Error(`postgres-baseline: generated ${BASELINE_MIGRATION_NAME} failed the static audit:\n  - ${findings.join("\n  - ")}`)
  const existing = existsSync(POSTGRES_INIT_SQL_PATH) ? readFileSync(POSTGRES_INIT_SQL_PATH, "utf8") : null
  const action = reconcileBaseline(existing, sql)
  if (action === "unchanged") {
    out(`[postgres-baseline] ${BASELINE_MIGRATION_NAME} unchanged sha256=${sha256(sql)}`)
    return
  }
  mkdirSync(dirname(POSTGRES_INIT_SQL_PATH), { recursive: true })
  writeFileSync(POSTGRES_INIT_SQL_PATH, sql)
  writeFileSync(join(POSTGRES_MIGRATIONS_DIR, "migration_lock.toml"), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n')
  const c = countBaseline(sql)
  out(`[postgres-baseline] wrote ${POSTGRES_INIT_SQL_PATH} sha256=${sha256(sql)} tables=${c.createTable} indexes=${c.createIndex + c.createUniqueIndex} (unique ${c.createUniqueIndex}) fks=${c.foreignKeys} cascade=${c.onDeleteCascade} setnull=${c.onDeleteSetNull}`)
}

function assertLocalPostgresUrl(url: string): void {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    throw new Error("postgres-baseline: POSTGRES_DIRECT_URL is not a valid URL")
  }
  if (parsed.protocol !== "postgresql:" && parsed.protocol !== "postgres:") {
    throw new Error(`postgres-baseline: POSTGRES_DIRECT_URL must be a postgresql:// URL (got scheme ${parsed.protocol})`)
  }
  const host = parsed.hostname
  const loopback = host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "[::1]"
  if (!loopback && process.env.POSTGRES_VERIFY_ALLOW_REMOTE !== "1") {
    throw new Error("postgres-baseline: verify only runs against a LOOPBACK PostgreSQL by default (an ephemeral, empty database). POSTGRES_VERIFY_ALLOW_REMOTE=1 bypasses ONLY this hostname check — never the empty-database, ledger or immutability requirements — and is meant for a disposable non-production database, never Neon production.")
  }
}

export function commandVerify(): void {
  const url = process.env.POSTGRES_DIRECT_URL
  if (!url) throw new Error("postgres-baseline: POSTGRES_DIRECT_URL is not set (point it at an EMPTY, ephemeral local PostgreSQL database)")
  assertLocalPostgresUrl(url)
  const env = { POSTGRES_DIRECT_URL: url }

  // 1. Derivation: the variant on disk equals a fresh derivation of the canonical schema.
  assertVariantFresh()
  out("[postgres-baseline] 1/7 variant derivation: OK")

  // 2. The baseline exists and is audit-clean.
  if (!existsSync(POSTGRES_INIT_SQL_PATH)) throw new Error(`postgres-baseline: ${POSTGRES_INIT_SQL_PATH} is missing — run generate-init`)
  const existing = readFileSync(POSTGRES_INIT_SQL_PATH, "utf8")
  const findings = auditBaselineSql(existing)
  if (findings.length > 0) throw new Error(`postgres-baseline: ${BASELINE_MIGRATION_NAME} failed the static audit:\n  - ${findings.join("\n  - ")}`)
  out(`[postgres-baseline] 2/7 ${BASELINE_MIGRATION_NAME} present and audit-clean sha256=${sha256(existing)}`)

  // 3. READ-ONLY preflight, BEFORE any DDL: the database must be empty.
  try {
    runAssertion(EMPTY_DATABASE_ASSERTION_SQL, env)
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err)
    const match = /POSTGRES_BASELINE_NOT_EMPTY: [^\n]*/.exec(detail)
    throw new Error(`postgres-baseline: db:postgres:verify requires an EMPTY disposable database and refused to touch this one — ${match ? match[0] : detail}`)
  }
  const fromEmpty = runPrisma(["migrate", "diff", "--from-empty", "--to-config-datasource", "--script", "--config", POSTGRES_CONFIG_PATH], env)
  if (!isEmptyDiff(fromEmpty)) {
    throw new Error("postgres-baseline: db:postgres:verify requires an EMPTY disposable database — `migrate diff --from-empty --to-config-datasource` is not empty, nothing was applied")
  }
  out("[postgres-baseline] 3/7 preflight: database is EMPTY (read-only check, no DDL executed)")

  // 4. Apply from zero — 0_init must be applied by THIS invocation.
  const deploy1 = runPrisma(["migrate", "deploy", "--config", POSTGRES_CONFIG_PATH], env)
  assertFirstDeployApplied(deploy1)
  out(`[postgres-baseline] 4/7 migrate deploy applied ${BASELINE_MIGRATION_NAME} now: OK`)

  // 5. Ledger: exactly one completed, single-step, non-rolled-back 0_init row.
  try {
    runAssertion(LEDGER_ASSERTION_SQL, env)
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err)
    const match = /POSTGRES_BASELINE_LEDGER_INVALID: [^\n]*/.exec(detail)
    throw new Error(`postgres-baseline: migration ledger is not the expected single ${BASELINE_MIGRATION_NAME} row — ${match ? match[0] : detail}`)
  }
  out(`[postgres-baseline] 5/7 ledger: exactly one completed ${BASELINE_MIGRATION_NAME} row (applied_steps_count=1, finished, not rolled back)`)

  // 6. Applied database ↔ variant must be an empty diff (explicit PostgreSQL config: no cross-provider diff possible).
  const diff = runPrisma(["migrate", "diff", "--from-config-datasource", "--to-schema", POSTGRES_SCHEMA_PATH, "--script", "--config", POSTGRES_CONFIG_PATH], env)
  if (!isEmptyDiff(diff)) throw new Error(`postgres-baseline: applied database differs from the PostgreSQL variant:\n${redactConnectionUrls(diff)}`)
  out("[postgres-baseline] 6/7 applied DB → variant diff: EMPTY")

  // 7. Second deploy is a no-op.
  assertRedeployNoop(runPrisma(["migrate", "deploy", "--config", POSTGRES_CONFIG_PATH], env))
  out("[postgres-baseline] 7/7 second migrate deploy: no-op")
  out("[postgres-baseline] OK — EMPTY → 0_init applied now → ledger correct → schema equals target → redeploy no-op")
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const [command, ...rest] = process.argv.slice(2)
  try {
    if (rest.length > 0) throw new Error(`postgres-baseline: unexpected argument(s): ${rest.join(" ")} (this tool takes no flags)`)
    switch (command) {
      case "generate-schema":
        commandGenerateSchema()
        break
      case "generate-init":
        commandGenerateInit()
        break
      case "verify":
        commandVerify()
        break
      default:
        throw new Error("usage: postgres-baseline.ts <generate-schema|generate-init|verify>")
    }
  } catch (err) {
    console.error(`[postgres-baseline] FAIL: ${err instanceof Error ? err.message : String(err)}`)
    process.exit(1)
  }
}
