/**
 * PostgreSQL baseline tooling (NEON-02).
 *
 * ONE canonical schema, ONE derived variant, ONE generated history:
 *
 *   prisma/schema.prisma                       canonical (SQLite provider while Turso is the runtime)
 *     └─ generate-schema ─▶ generated/schema.postgres.prisma   derived: ONLY the datasource
 *                                                                provider and the client output
 *                                                                path differ (gitignored artefact)
 *          └─ generate-init ─▶ prisma/migrations-postgres/0_init/migration.sql
 *                                                                empty → target, produced by
 *                                                                `prisma migrate diff`, audited
 *               └─ verify ─▶ applied from zero to an EMPTY local PostgreSQL, ledger checked,
 *                             `migrate diff` applied-DB → variant must be EMPTY, second deploy no-op
 *
 * The variant is never hand-edited: `verify` regenerates it in memory and fails
 * on any difference, so the PostgreSQL target cannot drift from the canonical
 * schema unnoticed. The SQLite history (`prisma/migrations`) and the PostgreSQL
 * history (`prisma/migrations-postgres`) never share a directory: Prisma 7.4.1
 * does NOT refuse a cross-provider diff (it silently emits DROP/CREATE), so the
 * provider separation is enforced here and by `prisma.config.postgres.ts`.
 *
 * Safety: `verify` refuses any database host that is not loopback unless
 * POSTGRES_VERIFY_ALLOW_REMOTE=1 is set explicitly; Turso/DATABASE_* variables
 * are removed from every child process; nothing here reads or writes Turso.
 *
 * CLI:
 *   tsx scripts/postgres-baseline.ts generate-schema
 *   tsx scripts/postgres-baseline.ts generate-init [--force]
 *   POSTGRES_DIRECT_URL=postgresql://…@127.0.0.1:5432/empty tsx scripts/postgres-baseline.ts verify
 */

import { execFileSync } from "node:child_process"
import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")

export const CANONICAL_SCHEMA_PATH = join(REPO_ROOT, "prisma", "schema.prisma")
export const POSTGRES_SCHEMA_PATH = join(REPO_ROOT, "generated", "schema.postgres.prisma")
export const POSTGRES_MIGRATIONS_DIR = join(REPO_ROOT, "prisma", "migrations-postgres")
export const POSTGRES_INIT_SQL_PATH = join(POSTGRES_MIGRATIONS_DIR, "0_init", "migration.sql")
export const POSTGRES_CONFIG_PATH = join(REPO_ROOT, "prisma.config.postgres.ts")
/** Relative to the generated schema file, i.e. `generated/prisma-postgres` — never the runtime client dir. */
export const POSTGRES_CLIENT_OUTPUT = "../generated/prisma-postgres"

const HEADER = [
  "// GENERATED by scripts/postgres-baseline.ts — DO NOT EDIT.",
  "// Derived from prisma/schema.prisma: only the datasource provider and the",
  "// generator output path differ. Regenerate with `npm run db:postgres:schema`.",
]

export function sha256(text: string | Buffer): string {
  return createHash("sha256").update(text).digest("hex")
}

/**
 * Derive the PostgreSQL variant from the canonical schema text. Exactly one
 * `provider = "sqlite"` datasource line and exactly one generator `output`
 * line are rewritten; anything else is a hard failure (fail closed rather than
 * guess). Returns the variant and the list of rewritten line numbers.
 */
export function derivePostgresSchema(canonical: string): { schema: string; rewrittenLines: number[] } {
  const lines = canonical.split("\n")
  const providerLines: number[] = []
  const outputLines: number[] = []
  let inDatasource = false
  let inGenerator = false
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (/^datasource\s+\w+\s*\{/.test(line)) inDatasource = true
    else if (/^generator\s+\w+\s*\{/.test(line)) inGenerator = true
    else if (/^\}/.test(line)) {
      inDatasource = false
      inGenerator = false
    }
    if (inDatasource && /^\s*provider\s*=\s*"[^"]+"\s*$/.test(line)) providerLines.push(i)
    if (inGenerator && /^\s*output\s*=\s*"[^"]+"\s*$/.test(line)) outputLines.push(i)
  }
  if (providerLines.length !== 1) {
    throw new Error(`postgres-baseline: expected exactly one datasource provider line, found ${providerLines.length}`)
  }
  if (outputLines.length !== 1) {
    throw new Error(`postgres-baseline: expected exactly one generator output line, found ${outputLines.length}`)
  }
  const providerLine = lines[providerLines[0]]
  if (!/"sqlite"/.test(providerLine)) {
    throw new Error(`postgres-baseline: canonical provider is not "sqlite" — the runtime provider flip must be an explicit mission, not a derivation`)
  }
  const out = [...lines]
  out[providerLines[0]] = providerLine.replace('"sqlite"', '"postgresql"')
  out[outputLines[0]] = lines[outputLines[0]].replace(/"[^"]+"/, `"${POSTGRES_CLIENT_OUTPUT}"`)
  return { schema: [...HEADER, ...out].join("\n"), rewrittenLines: [providerLines[0] + 1, outputLines[0] + 1] }
}

/** SQLite constructs that must never appear in the PostgreSQL baseline. */
export const SQLITE_REMNANT_PATTERNS: ReadonlyArray<{ name: string; regex: RegExp }> = [
  { name: "PRAGMA", regex: /\bPRAGMA\b/i },
  { name: "DATETIME type", regex: /\bDATETIME\b/i },
  { name: "AUTOINCREMENT", regex: /\bAUTOINCREMENT\b/i },
  { name: "rowid", regex: /\browid\b/i },
  { name: "sqlite_ internals", regex: /\bsqlite_/i },
  { name: "table rebuild (new_ prefix)", regex: /CREATE TABLE "new_/ },
  { name: "INSERT INTO (data copy)", regex: /\bINSERT INTO\b/i },
  { name: "RENAME TO", regex: /\bRENAME TO\b/i },
  { name: "DROP TABLE", regex: /\bDROP TABLE\b/i },
  { name: "? placeholder", regex: /\?/ },
  { name: "strftime()", regex: /\bstrftime\s*\(/i },
  { name: "datetime()", regex: /\bdatetime\s*\(/i },
  { name: "json_extract()", regex: /\bjson_extract\s*\(/i },
]

/** PostgreSQL constructs that the fidelity-first target does not use. */
export const UNEXPECTED_POSTGRES_PATTERNS: ReadonlyArray<{ name: string; regex: RegExp }> = [
  { name: "SERIAL", regex: /\bSERIAL\b/ },
  { name: "IDENTITY", regex: /GENERATED .* AS IDENTITY/ },
  { name: "JSONB", regex: /\bJSONB\b/ },
  { name: "CREATE TYPE (enum)", regex: /\bCREATE TYPE\b/ },
  { name: "gen_random_uuid", regex: /gen_random_uuid/ },
  { name: "UUID type", regex: /\bUUID\b/ },
  { name: "DEFERRABLE", regex: /\bDEFERRABLE\b/ },
  { name: "CREATE EXTENSION", regex: /\bCREATE EXTENSION\b/ },
  { name: "TIMESTAMPTZ", regex: /\bTIMESTAMPTZ\b|WITH TIME ZONE/ },
  { name: "NUMERIC/DECIMAL", regex: /\b(NUMERIC|DECIMAL)\b/ },
]

export interface BaselineCounts {
  createTable: number
  createIndex: number
  createUniqueIndex: number
  foreignKeys: number
  onDeleteCascade: number
  onDeleteSetNull: number
  onDeleteRestrict: number
  primaryKeys: number
}

export function countBaseline(sql: string): BaselineCounts {
  const count = (re: RegExp) => (sql.match(re) ?? []).length
  return {
    createTable: count(/^CREATE TABLE /gm),
    createIndex: count(/^CREATE INDEX /gm),
    createUniqueIndex: count(/^CREATE UNIQUE INDEX /gm),
    foreignKeys: count(/FOREIGN KEY/g),
    onDeleteCascade: count(/ON DELETE CASCADE/g),
    onDeleteSetNull: count(/ON DELETE SET NULL/g),
    onDeleteRestrict: count(/ON DELETE RESTRICT/g),
    primaryKeys: count(/PRIMARY KEY/g),
  }
}

/** Static audit of a generated baseline: SQLite remnants and unexpected PostgreSQL constructs. */
export function auditBaselineSql(sql: string): string[] {
  const findings: string[] = []
  for (const { name, regex } of SQLITE_REMNANT_PATTERNS) if (regex.test(sql)) findings.push(`SQLite remnant: ${name}`)
  for (const { name, regex } of UNEXPECTED_POSTGRES_PATTERNS) if (regex.test(sql)) findings.push(`unexpected PostgreSQL construct: ${name}`)
  const identifiersOver63 = new Set((sql.match(/"[A-Za-z0-9_]{64,}"/g) ?? []).map((s) => s.slice(1, -1)))
  for (const ident of identifiersOver63) findings.push(`identifier longer than 63 characters (PostgreSQL would truncate): ${ident}`)
  return findings
}

// ─── Process helpers ────────────────────────────────────────────────────────

function sanitizedEnv(extra: Record<string, string> = {}): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env, ...extra }
  delete env.DATABASE_URL
  delete env.TURSO_DATABASE_URL
  delete env.DATABASE_AUTH_TOKEN
  delete env.TURSO_AUTH_TOKEN
  env.DOTENV_CONFIG_PATH = "/dev/null"
  env.CHECKPOINT_DISABLE = "1"
  env.PRISMA_HIDE_UPDATE_MESSAGE = "1"
  return env
}

function runPrisma(args: string[], extraEnv: Record<string, string> = {}): string {
  return execFileSync(join(REPO_ROOT, "node_modules", ".bin", "prisma"), args, {
    cwd: REPO_ROOT,
    env: sanitizedEnv(extraEnv),
    stdio: ["ignore", "pipe", "pipe"],
    encoding: "utf8",
  })
}

function out(line: string): void {
  process.stdout.write(`${line}\n`)
}

// ─── Commands ───────────────────────────────────────────────────────────────

export function commandGenerateSchema(): string {
  const canonical = readFileSync(CANONICAL_SCHEMA_PATH, "utf8")
  const { schema, rewrittenLines } = derivePostgresSchema(canonical)
  mkdirSync(dirname(POSTGRES_SCHEMA_PATH), { recursive: true })
  writeFileSync(POSTGRES_SCHEMA_PATH, schema)
  out(`[postgres-baseline] wrote ${POSTGRES_SCHEMA_PATH} (rewrote canonical lines ${rewrittenLines.join(", ")}) sha256=${sha256(schema)}`)
  return schema
}

function assertVariantFresh(): string {
  if (!existsSync(POSTGRES_SCHEMA_PATH)) throw new Error("postgres-baseline: generated/schema.postgres.prisma is missing — run generate-schema first")
  const onDisk = readFileSync(POSTGRES_SCHEMA_PATH, "utf8")
  const fresh = derivePostgresSchema(readFileSync(CANONICAL_SCHEMA_PATH, "utf8")).schema
  if (onDisk !== fresh) throw new Error("postgres-baseline: generated/schema.postgres.prisma is STALE or hand-edited — it differs from a fresh derivation of prisma/schema.prisma")
  return onDisk
}

export function commandGenerateInit(force = false): void {
  assertVariantFresh()
  const sql = runPrisma(["migrate", "diff", "--from-empty", "--to-schema", POSTGRES_SCHEMA_PATH, "--script"])
  const findings = auditBaselineSql(sql)
  if (findings.length > 0) throw new Error(`postgres-baseline: generated 0_init failed the static audit:\n  - ${findings.join("\n  - ")}`)
  if (existsSync(POSTGRES_INIT_SQL_PATH) && !force) {
    const existing = readFileSync(POSTGRES_INIT_SQL_PATH, "utf8")
    if (existing !== sql) {
      throw new Error(
        `postgres-baseline: 0_init already exists and DIFFERS from a fresh generation (existing sha256=${sha256(existing)}, fresh sha256=${sha256(sql)}). A baseline is immutable once published; new schema changes belong in a new PostgreSQL migration. Use --force only before the baseline has ever been applied anywhere.`,
      )
    }
    out(`[postgres-baseline] 0_init unchanged sha256=${sha256(sql)}`)
    return
  }
  mkdirSync(dirname(POSTGRES_INIT_SQL_PATH), { recursive: true })
  writeFileSync(POSTGRES_INIT_SQL_PATH, sql)
  writeFileSync(join(POSTGRES_MIGRATIONS_DIR, "migration_lock.toml"), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n')
  const c = countBaseline(sql)
  out(`[postgres-baseline] wrote ${POSTGRES_INIT_SQL_PATH} sha256=${sha256(sql)} tables=${c.createTable} indexes=${c.createIndex + c.createUniqueIndex} (unique ${c.createUniqueIndex}) fks=${c.foreignKeys} cascade=${c.onDeleteCascade} setnull=${c.onDeleteSetNull}`)
}

function assertLocalPostgresUrl(url: string): void {
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    throw new Error("postgres-baseline: POSTGRES_DIRECT_URL is not a valid URL")
  }
  if (parsed.protocol !== "postgresql:" && parsed.protocol !== "postgres:") {
    throw new Error(`postgres-baseline: POSTGRES_DIRECT_URL must be a postgresql:// URL (got scheme ${parsed.protocol})`)
  }
  const host = parsed.hostname
  const loopback = host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "[::1]"
  if (!loopback && process.env.POSTGRES_VERIFY_ALLOW_REMOTE !== "1") {
    throw new Error("postgres-baseline: verify only runs against a LOOPBACK PostgreSQL by default (an ephemeral, empty database). Set POSTGRES_VERIFY_ALLOW_REMOTE=1 only for a disposable non-production database — never Neon production.")
  }
}

export function commandVerify(): void {
  const url = process.env.POSTGRES_DIRECT_URL
  if (!url) throw new Error("postgres-baseline: POSTGRES_DIRECT_URL is not set (point it at an EMPTY, ephemeral local PostgreSQL database)")
  assertLocalPostgresUrl(url)
  // 1. Derivation: the variant on disk equals a fresh derivation of the canonical schema.
  assertVariantFresh()
  out("[postgres-baseline] 1/5 variant derivation: OK")
  // 2. The baseline exists and is what the variant generates today (empty → variant), and is audit-clean.
  if (!existsSync(POSTGRES_INIT_SQL_PATH)) throw new Error("postgres-baseline: prisma/migrations-postgres/0_init/migration.sql is missing — run generate-init")
  const existing = readFileSync(POSTGRES_INIT_SQL_PATH, "utf8")
  const findings = auditBaselineSql(existing)
  if (findings.length > 0) throw new Error(`postgres-baseline: 0_init failed the static audit:\n  - ${findings.join("\n  - ")}`)
  out(`[postgres-baseline] 2/5 0_init present and audit-clean sha256=${sha256(existing)}`)
  // 3. Apply from zero.
  const deploy1 = runPrisma(["migrate", "deploy", "--config", POSTGRES_CONFIG_PATH], { POSTGRES_DIRECT_URL: url })
  if (!/successfully applied|No pending migrations/.test(deploy1)) throw new Error(`postgres-baseline: unexpected migrate deploy output:\n${deploy1}`)
  out("[postgres-baseline] 3/5 migrate deploy from zero: OK")
  // 4. Applied database ↔ variant must be an empty diff (explicit PostgreSQL config: no cross-provider diff possible).
  const diff = runPrisma(["migrate", "diff", "--from-config-datasource", "--to-schema", POSTGRES_SCHEMA_PATH, "--script", "--config", POSTGRES_CONFIG_PATH], { POSTGRES_DIRECT_URL: url })
  const diffBody = diff.split("\n").filter((l) => l.trim() && !/^-- This is an empty migration/.test(l) && !/^Loaded Prisma config/.test(l))
  if (diffBody.length > 0) throw new Error(`postgres-baseline: applied database differs from the PostgreSQL variant:\n${diffBody.join("\n")}`)
  out("[postgres-baseline] 4/5 applied DB → variant diff: EMPTY")
  // 5. Second deploy is a no-op.
  const deploy2 = runPrisma(["migrate", "deploy", "--config", POSTGRES_CONFIG_PATH], { POSTGRES_DIRECT_URL: url })
  if (!/No pending migrations/.test(deploy2)) throw new Error(`postgres-baseline: second migrate deploy was not a no-op:\n${deploy2}`)
  out("[postgres-baseline] 5/5 second migrate deploy: no-op")
  out("[postgres-baseline] OK — migrations-postgres applied from zero equals the PostgreSQL target schema")
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  const [command, ...flags] = process.argv.slice(2)
  try {
    switch (command) {
      case "generate-schema":
        commandGenerateSchema()
        break
      case "generate-init":
        commandGenerateInit(flags.includes("--force"))
        break
      case "verify":
        commandVerify()
        break
      default:
        throw new Error("usage: postgres-baseline.ts <generate-schema|generate-init [--force]|verify>")
    }
  } catch (err) {
    console.error(`[postgres-baseline] FAIL: ${err instanceof Error ? err.message : String(err)}`)
    process.exit(1)
  }
}
